import './ui/globals.css';

import type { Metadata } from 'next';

import { Toaster } from '@/components/ui/sonner';

import { ThemeProvider } from '@/components/theme-provider';

import { cn } from '@/lib/utils';

import { fontMono, fontSans } from './ui/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          'bg-background group/body min-h-svh overscroll-none font-sans antialiased',
          fontSans.variable,
          fontMono.variable
        )}
      >
       
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <Toaster />
          </ThemeProvider>
       
      </body>
    </html>
  );
}
